version: '2'
services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
  web:
    build: .
    ports:
      - "3000:3000"
  n8n:
    image: n8nio/n8n:0.35.0
    ports:
      - "5679:5678"
    environment:
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://mongo:27017/workflow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - n8n-data:/root/.n8n
    command: /bin/sh -c "sleep 5; n8n start"
volumes:
  n8n-data:
  mongodb-data: